# Generated by Django 5.2.4 on 2025-07-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_enrollment_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, help_text='Optional certificate description'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiry date', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file_url',
            field=models.URLField(blank=True, help_text='URL to the certificate PDF', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], db_index=True, default='ISSUED', max_length=10),
        ),
    ]
