# Generated by Django 5.2.4 on 2025-12-03 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("courses", "0003_add_file_to_contentitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="LTIPlatform",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this platform",
                        max_length=255,
                    ),
                ),
                (
                    "issuer",
                    models.URLField(
                        help_text="Platform issuer URL (iss claim in JWT)",
                        max_length=500,
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="OAuth2 client ID assigned by the platform",
                        max_length=255,
                    ),
                ),
                (
                    "deployment_id",
                    models.CharField(
                        blank=True,
                        help_text="Deployment ID (optional, some platforms use multiple)",
                        max_length=255,
                    ),
                ),
                (
                    "auth_login_url",
                    models.URLField(
                        help_text="Platform's OIDC authorization endpoint",
                        max_length=500,
                    ),
                ),
                (
                    "auth_token_url",
                    models.URLField(
                        help_text="Platform's OAuth2 token endpoint", max_length=500
                    ),
                ),
                (
                    "keyset_url",
                    models.URLField(
                        help_text="Platform's public keyset (JWKS) URL", max_length=500
                    ),
                ),
                (
                    "tool_private_key",
                    models.TextField(
                        help_text="PEM-encoded private key for signing messages to this platform"
                    ),
                ),
                (
                    "tool_public_key",
                    models.TextField(
                        help_text="PEM-encoded public key for the platform to verify our signatures"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant this LTI platform belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lti_platforms",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "LTI Platform",
                "verbose_name_plural": "LTI Platforms",
                "ordering": ["tenant__name", "name"],
                "unique_together": {("tenant", "issuer", "client_id")},
            },
        ),
        migrations.CreateModel(
            name="SSOConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this SSO provider",
                        max_length=255,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("SAML", "SAML 2.0"),
                            ("OAUTH_GOOGLE", "Google OAuth 2.0"),
                            ("OAUTH_MICROSOFT", "Microsoft OAuth 2.0"),
                            ("OAUTH_GENERIC", "Generic OAuth 2.0"),
                            ("OIDC", "OpenID Connect"),
                        ],
                        help_text="Type of SSO provider",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="If true, users will be redirected here by default for SSO login",
                    ),
                ),
                (
                    "idp_entity_id",
                    models.CharField(
                        blank=True,
                        help_text="SAML Identity Provider Entity ID",
                        max_length=500,
                    ),
                ),
                (
                    "idp_sso_url",
                    models.URLField(
                        blank=True,
                        help_text="SAML IdP Single Sign-On URL",
                        max_length=500,
                    ),
                ),
                (
                    "idp_slo_url",
                    models.URLField(
                        blank=True,
                        help_text="SAML IdP Single Logout URL (optional)",
                        max_length=500,
                    ),
                ),
                (
                    "idp_x509_cert",
                    models.TextField(
                        blank=True, help_text="SAML IdP X.509 certificate (PEM format)"
                    ),
                ),
                (
                    "oauth_client_id",
                    models.CharField(
                        blank=True, help_text="OAuth/OIDC Client ID", max_length=255
                    ),
                ),
                (
                    "oauth_client_secret",
                    models.CharField(
                        blank=True,
                        help_text="OAuth/OIDC Client Secret (encrypted in production)",
                        max_length=500,
                    ),
                ),
                (
                    "oauth_authorization_url",
                    models.URLField(
                        blank=True,
                        help_text="OAuth authorization endpoint URL",
                        max_length=500,
                    ),
                ),
                (
                    "oauth_token_url",
                    models.URLField(
                        blank=True, help_text="OAuth token endpoint URL", max_length=500
                    ),
                ),
                (
                    "oauth_userinfo_url",
                    models.URLField(
                        blank=True,
                        help_text="OAuth/OIDC userinfo endpoint URL",
                        max_length=500,
                    ),
                ),
                (
                    "oauth_scopes",
                    models.CharField(
                        blank=True,
                        default="openid email profile",
                        help_text="Space-separated list of OAuth scopes",
                        max_length=500,
                    ),
                ),
                (
                    "attribute_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON mapping of IdP attributes to user fields (e.g., {'email': 'mail', 'first_name': 'givenName'})",
                    ),
                ),
                (
                    "role_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON mapping of IdP groups to LMS roles (e.g., {'admins': 'ADMIN', 'teachers': 'INSTRUCTOR'})",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant this SSO configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_configurations",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "SSO Configuration",
                "verbose_name_plural": "SSO Configurations",
                "ordering": ["tenant__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="LTIDeployment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deployment_id",
                    models.CharField(
                        help_text="Deployment ID provided by the platform",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="core.ltiplatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "LTI Deployment",
                "verbose_name_plural": "LTI Deployments",
                "unique_together": {("platform", "deployment_id")},
            },
        ),
        migrations.CreateModel(
            name="LTIResourceLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_link_id",
                    models.CharField(
                        help_text="Resource link ID from LTI launch", max_length=255
                    ),
                ),
                (
                    "lti_context_id",
                    models.CharField(
                        blank=True,
                        help_text="LTI context ID (typically course ID)",
                        max_length=255,
                    ),
                ),
                (
                    "lti_context_title",
                    models.CharField(
                        blank=True, help_text="LTI context title", max_length=500
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked LMS course",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lti_resource_links",
                        to="courses.course",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_links",
                        to="core.ltiplatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "LTI Resource Link",
                "verbose_name_plural": "LTI Resource Links",
                "unique_together": {("platform", "resource_link_id")},
            },
        ),
    ]
