# Generated by Django 5.2.4 on 2025-12-04 04:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lti_sso_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='LMS Platform', help_text='The name of the platform displayed to users', max_length=100)),
                ('site_description', models.TextField(blank=True, help_text='A brief description of the platform', max_length=500)),
                ('default_language', models.CharField(default='en', help_text='Default language code (e.g., en, es, fr)', max_length=10)),
                ('timezone', models.CharField(default='UTC', help_text='Default timezone (e.g., UTC, America/New_York)', max_length=50)),
                ('support_email', models.EmailField(blank=True, help_text='Support contact email address', max_length=254)),
                ('terms_url', models.URLField(blank=True, help_text='URL to Terms of Service page')),
                ('privacy_url', models.URLField(blank=True, help_text='URL to Privacy Policy page')),
                ('logo_url', models.URLField(blank=True, help_text='URL to the platform logo image')),
                ('favicon_url', models.URLField(blank=True, help_text='URL to the platform favicon')),
                ('storage_backend', models.CharField(choices=[('local', 'Local Filesystem'), ('s3', 'Amazon S3 / S3-Compatible'), ('gcs', 'Google Cloud Storage'), ('azure', 'Azure Blob Storage')], default='local', help_text='File storage backend type', max_length=20)),
                ('s3_bucket_name', models.CharField(blank=True, max_length=255)),
                ('s3_region', models.CharField(blank=True, default='us-east-1', max_length=50)),
                ('s3_access_key_id', models.CharField(blank=True, max_length=255)),
                ('s3_secret_access_key', models.CharField(blank=True, max_length=255)),
                ('s3_endpoint_url', models.URLField(blank=True, help_text='Custom endpoint for S3-compatible services')),
                ('s3_custom_domain', models.CharField(blank=True, help_text='CDN or custom domain', max_length=255)),
                ('gcs_bucket_name', models.CharField(blank=True, max_length=255)),
                ('gcs_project_id', models.CharField(blank=True, max_length=255)),
                ('azure_container_name', models.CharField(blank=True, max_length=255)),
                ('azure_account_name', models.CharField(blank=True, max_length=255)),
                ('azure_account_key', models.CharField(blank=True, max_length=255)),
                ('max_file_size_mb', models.PositiveIntegerField(default=50, help_text='Maximum file upload size in MB')),
                ('allowed_extensions', models.CharField(default='pdf,doc,docx,ppt,pptx,xls,xlsx,jpg,jpeg,png,gif,mp4,webm,mp3,zip', help_text='Comma-separated list of allowed file extensions', max_length=500)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
                ('default_from_name', models.CharField(blank=True, max_length=255)),
                ('email_timeout', models.PositiveIntegerField(default=30, help_text='Email connection timeout in seconds')),
                ('tenant', models.OneToOneField(blank=True, help_text='Tenant these settings belong to. Null for global/default settings.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_settings', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
