# Generated by Django 5.2.4 on 2025-12-08 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('core', '0003_platform_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LTILineItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_item_id', models.CharField(blank=True, help_text='Line item ID/URL from the LTI platform', max_length=500)),
                ('label', models.CharField(help_text='Display name for the line item', max_length=255)),
                ('score_maximum', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximum score for this line item', max_digits=10)),
                ('tag', models.CharField(blank=True, help_text='Optional tag for categorizing line items', max_length=255)),
                ('resource_id', models.CharField(blank=True, help_text='Tool resource identifier', max_length=255)),
                ('ags_endpoint', models.URLField(blank=True, help_text='AGS endpoint URL for this line item', max_length=500)),
                ('assessment', models.ForeignKey(blank=True, help_text='Linked LMS assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lti_line_items', to='assessments.assessment')),
                ('resource_link', models.ForeignKey(help_text='The resource link this line item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.ltiresourcelink')),
            ],
            options={
                'verbose_name': 'LTI Line Item',
                'verbose_name_plural': 'LTI Line Items',
                'unique_together': {('resource_link', 'line_item_id')},
            },
        ),
        migrations.CreateModel(
            name='LTIGradeSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lti_user_id', models.CharField(help_text='LTI user identifier (sub claim from launch)', max_length=255)),
                ('score', models.DecimalField(decimal_places=2, help_text='Score achieved', max_digits=10)),
                ('score_maximum', models.DecimalField(decimal_places=2, help_text='Maximum possible score', max_digits=10)),
                ('comment', models.TextField(blank=True, help_text='Optional comment/feedback')),
                ('activity_progress', models.CharField(default='Completed', help_text='Activity progress (Initialized, Started, InProgress, Submitted, Completed)', max_length=50)),
                ('grading_progress', models.CharField(default='FullyGraded', help_text='Grading progress (FullyGraded, Pending, PendingManual, Failed, NotReady)', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the grade was successfully submitted to the platform', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if submission failed')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('user', models.ForeignKey(help_text='The user this grade is for', on_delete=django.db.models.deletion.CASCADE, related_name='lti_grade_submissions', to=settings.AUTH_USER_MODEL)),
                ('line_item', models.ForeignKey(help_text='The line item this grade belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='grade_submissions', to='core.ltilineitem')),
            ],
            options={
                'verbose_name': 'LTI Grade Submission',
                'verbose_name_plural': 'LTI Grade Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
