# Generated by Django 5.2 on 2025-04-15 00:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier for the course URL', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for categorization')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['INSTRUCTOR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_authored', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.tenant')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the module within the course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ['course', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('TEXT', 'Text'), ('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('URL', 'External URL'), ('H5P', 'H5P Content'), ('SCORM', 'SCORM Package'), ('QUIZ', 'Quiz / Assessment')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the content within the module')),
                ('text_content', models.TextField(blank=True, help_text='Markdown or HTML content', null=True)),
                ('external_url', models.URLField(blank=True, help_text='URL for external content', max_length=2048, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Type-specific metadata (e.g., video duration, quiz settings)')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='courses.module')),
            ],
            options={
                'ordering': ['module', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('comment', models.TextField(blank=True, help_text='Optional comment about changes in this version')),
                ('content_type', models.CharField(choices=[('TEXT', 'Text'), ('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('URL', 'External URL'), ('H5P', 'H5P Content'), ('SCORM', 'SCORM Package'), ('QUIZ', 'Quiz / Assessment')], max_length=20)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='courses.contentitem')),
                ('user', models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['content_item', '-version_number'],
                'unique_together': {('content_item', 'version_number')},
            },
        ),
    ]
