# Generated by Django 5.2.1 on 2025-07-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, help_text='Course category', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Course difficulty level', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=1, help_text='Estimated duration in hours'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Whether the course is free'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of learning objectives'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Course price (0 for free courses)', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Course thumbnail URL', max_length=2048, null=True),
        ),
    ]
