# Generated by Django 5.2.4 on 2025-12-03 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_category_course_difficulty_level_and_more"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="file",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated file for document, media, or package types",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_items",
                to="files.file",
            ),
        ),
    ]
