# Generated by Django 5.2.4 on 2025-12-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_file_to_contentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Whether this content item is required for course completion'),
        ),
    ]
