# Generated by Django 5.2.4 on 2025-12-17 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_content_item_is_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisite_type', models.CharField(choices=[('REQUIRED', 'Required'), ('RECOMMENDED', 'Recommended'), ('COREQUISITE', 'Corequisite')], default='REQUIRED', help_text='Type of prerequisite relationship', max_length=15)),
                ('minimum_completion_percentage', models.PositiveIntegerField(default=100, help_text='Minimum completion percentage required (0-100)')),
                ('course', models.ForeignKey(help_text='The course that has the prerequisite requirement', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.course')),
                ('prerequisite_course', models.ForeignKey(help_text='The course that must be completed first', on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Prerequisite',
                'verbose_name_plural': 'Course Prerequisites',
                'ordering': ['course', 'prerequisite_type', 'prerequisite_course__title'],
                'unique_together': {('course', 'prerequisite_course')},
            },
        ),
        migrations.CreateModel(
            name='ModulePrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisite_type', models.CharField(choices=[('REQUIRED', 'Required'), ('RECOMMENDED', 'Recommended'), ('COREQUISITE', 'Corequisite')], default='REQUIRED', help_text='Type of prerequisite relationship', max_length=15)),
                ('minimum_score', models.PositiveIntegerField(blank=True, help_text='Minimum score required in prerequisite module (0-100, null means completion only)', null=True)),
                ('module', models.ForeignKey(help_text='The module that has the prerequisite requirement', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.module')),
                ('prerequisite_module', models.ForeignKey(help_text='The module that must be completed first', on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='courses.module')),
            ],
            options={
                'verbose_name': 'Module Prerequisite',
                'verbose_name_plural': 'Module Prerequisites',
                'ordering': ['module', 'prerequisite_type', 'prerequisite_module__order'],
                'unique_together': {('module', 'prerequisite_module')},
            },
        ),
    ]
