# Generated by Django 5.2 on 2025-04-15 00:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assessment_type', models.CharField(choices=[('QUIZ', 'Quiz'), ('EXAM', 'Exam'), ('ASSIGNMENT', 'Assignment')], default='QUIZ', max_length=20)),
                ('grading_type', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual'), ('HYBRID', 'Hybrid')], default='AUTO', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes. Blank for no limit.', null=True)),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Maximum number of attempts allowed. 0 for unlimited.')),
                ('pass_mark_percentage', models.PositiveIntegerField(default=50, help_text='Minimum percentage score required to pass.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('show_results_immediately', models.BooleanField(default=True, help_text='Show score/feedback immediately after submission')),
                ('shuffle_questions', models.BooleanField(default=False, help_text='Randomize question order for each attempt')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course')),
            ],
            options={
                'ordering': ['course', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated score for the attempt', max_digits=5, null=True)),
                ('max_score', models.PositiveIntegerField(blank=True, help_text='Total possible points at time of attempt', null=True)),
                ('is_passed', models.BooleanField(blank=True, help_text='Whether the attempt met the pass mark', null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Overall feedback for the attempt (from instructor)')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assessment', 'user', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MC', 'Multiple Choice'), ('TF', 'True/False'), ('SA', 'Short Answer'), ('ES', 'Essay'), ('CODE', 'Code Submission'), ('MT', 'Matching'), ('FB', 'Fill in the Blanks')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the question within the assessment (if not shuffled)')),
                ('points', models.PositiveIntegerField(default=1, help_text='Points awarded for a correct answer')),
                ('type_specific_data', models.JSONField(blank=True, default=dict, help_text='Data specific to the question type (options, answers, etc.)')),
                ('feedback', models.TextField(blank=True, help_text='General feedback displayed after answering (optional)')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment')),
            ],
            options={
                'ordering': ['assessment', 'order'],
            },
        ),
    ]
