# Generated by Django 5.2.4 on 2025-12-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills evaluated by this question', related_name='questions', through='skills.AssessmentSkillMapping', to='skills.skill'),
        ),
    ]
