# Generated by Django 5.2.4 on 2025-12-17 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ltilineitem_ltigradesubmission'),
        ('courses', '0005_add_prerequisite_models'),
        ('learning_paths', '0002_learningpathprogress_learningpathstepprogress'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedLearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('generation_type', models.CharField(choices=[('SKILL_GAP', 'Skill Gap Based'), ('REMEDIAL', 'Remedial/Recovery'), ('GOAL_BASED', 'Goal Based'), ('ONBOARDING', 'Onboarding')], db_index=True, max_length=20)),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated duration in hours')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Path may become stale after this date', null=True)),
                ('generation_params', models.JSONField(blank=True, default=dict, help_text='Parameters used by the algorithm to generate this path')),
                ('target_skills', models.ManyToManyField(blank=True, help_text='Skills this path aims to develop', related_name='targeting_personalized_paths', to='skills.skill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_learning_paths', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personalized Learning Path',
                'verbose_name_plural': 'Personalized Learning Paths',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalizedPathProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('ABANDONED', 'Abandoned')], db_index=True, default='NOT_STARTED', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_step_order', models.PositiveIntegerField(default=0, help_text='Order of the current step (0 means not started)')),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='Timestamp of last user activity on this path', null=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning_paths.personalizedlearningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_path_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personalized Path Progress',
                'verbose_name_plural': 'Personalized Path Progress Records',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'path')},
            },
        ),
        migrations.CreateModel(
            name='PersonalizedPathStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(help_text='Order of this step within the path')),
                ('is_required', models.BooleanField(default=True, help_text='Is this step mandatory to complete the path?')),
                ('reason', models.TextField(blank=True, help_text='AI-generated explanation of why this module was included')),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated duration in minutes')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_path_steps', to='courses.module')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='learning_paths.personalizedlearningpath')),
                ('target_skills', models.ManyToManyField(blank=True, help_text='Specific skills this step addresses', related_name='personalized_path_steps', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Personalized Path Step',
                'verbose_name_plural': 'Personalized Path Steps',
                'ordering': ['path', 'order'],
                'unique_together': {('path', 'order')},
            },
        ),
    ]
