# Generated by Django 5.2.4 on 2025-12-08 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnergroup',
            name='members',
            field=models.ManyToManyField(related_name='learner_groups', through='users.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
