# Generated by Django 5.2.4 on 2025-12-17 11:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('core', '0004_ltilineitem_ltigradesubmission'),
        ('courses', '0005_add_prerequisite_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the skill', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the skill', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the skill')),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical'), ('SOFT', 'Soft Skills'), ('DOMAIN', 'Domain Knowledge'), ('LANGUAGE', 'Language'), ('METHODOLOGY', 'Methodology'), ('TOOL', 'Tool/Technology'), ('OTHER', 'Other')], db_index=True, default='OTHER', help_text='Category this skill belongs to', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this skill is actively used')),
                ('external_id', models.CharField(blank=True, help_text='External identifier (e.g., for skill frameworks like SFIA, ESCO)', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for additional categorization')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent skill for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='skills.skill')),
                ('tenant', models.ForeignKey(help_text='The tenant this skill belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ModuleSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_level', models.CharField(choices=[('INTRODUCES', 'Introduces'), ('DEVELOPS', 'Develops'), ('REINFORCES', 'Reinforces'), ('MASTERS', 'Masters')], default='DEVELOPS', help_text='How this module contributes to skill development', max_length=15)),
                ('proficiency_gained', models.PositiveIntegerField(default=10, help_text='Estimated proficiency points gained (1-100) upon module completion', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is a primary skill for the module')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of skill importance within the module')),
                ('module', models.ForeignKey(help_text='The module that teaches this skill', on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='courses.module')),
                ('skill', models.ForeignKey(help_text='The skill being taught', on_delete=django.db.models.deletion.CASCADE, related_name='module_mappings', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Module Skill Mapping',
                'verbose_name_plural': 'Module Skill Mappings',
                'ordering': ['module', '-is_primary', 'order'],
                'unique_together': {('module', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='LearnerSkillProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency_score', models.PositiveIntegerField(default=0, help_text='Current proficiency score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('proficiency_level', models.CharField(choices=[('NOVICE', 'Novice'), ('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='NOVICE', help_text='Current proficiency level', max_length=15)),
                ('progress_history', models.JSONField(blank=True, default=list, help_text='History of proficiency changes: [{date, score, source, source_id}]')),
                ('contributing_modules', models.JSONField(blank=True, default=list, help_text='List of module IDs that contributed to this skill')),
                ('contributing_assessments', models.JSONField(blank=True, default=list, help_text='List of assessment IDs that contributed to this skill')),
                ('last_assessed_at', models.DateTimeField(blank=True, help_text='When this skill was last formally assessed', null=True)),
                ('last_practiced_at', models.DateTimeField(blank=True, help_text='When this skill was last practiced/used', null=True)),
                ('user', models.ForeignKey(help_text='The learner', on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(help_text='The skill being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='learner_progress', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Learner Skill Progress',
                'verbose_name_plural': 'Learner Skill Progress',
                'ordering': ['-proficiency_score', 'skill__name'],
                'unique_together': {('user', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentSkillMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.PositiveIntegerField(default=1, help_text='How heavily this question weighs for the skill (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('proficiency_required', models.CharField(choices=[('NOVICE', 'Novice'), ('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', help_text='Minimum proficiency level required to answer correctly', max_length=15)),
                ('proficiency_demonstrated', models.CharField(choices=[('NOVICE', 'Novice'), ('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', help_text='Proficiency level demonstrated by correctly answering', max_length=15)),
                ('question', models.ForeignKey(help_text='The assessment question', on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='assessments.question')),
                ('skill', models.ForeignKey(help_text='The skill being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='assessment_mappings', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Assessment Skill Mapping',
                'verbose_name_plural': 'Assessment Skill Mappings',
                'ordering': ['question', 'skill'],
                'unique_together': {('question', 'skill')},
            },
        ),
    ]
