# Generated by Django 5.2 on 2025-04-15 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier for API access', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuration for generating the report')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Report Definition',
                'verbose_name_plural': 'Report Definitions',
                'ordering': ['tenant__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Dashboard Definition',
                'verbose_name_plural': 'Dashboard Definitions',
                'ordering': ['tenant__name', 'name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('USER_REGISTER', 'User Registration'), ('COURSE_VIEW', 'Course Viewed'), ('COURSE_ENROLL', 'Course Enrollment'), ('COURSE_COMPLETE', 'Course Completion'), ('MODULE_VIEW', 'Module Viewed'), ('CONTENT_VIEW', 'Content Item Viewed'), ('CONTENT_COMPLETE', 'Content Item Completion'), ('ASSESSMENT_START', 'Assessment Started'), ('ASSESSMENT_SUBMIT', 'Assessment Submitted'), ('ASSESSMENT_PASS', 'Assessment Passed'), ('ASSESSMENT_FAIL', 'Assessment Failed'), ('FILE_DOWNLOAD', 'File Downloaded'), ('CERTIFICATE_VIEW', 'Certificate Viewed')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tracked Event',
                'verbose_name_plural': 'Tracked Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'event_type', 'created_at'], name='analytics_e_tenant__d610c0_idx'), models.Index(fields=['user', 'event_type', 'created_at'], name='analytics_e_user_id_ed1d3e_idx')],
            },
        ),
    ]
