# Generated by Django 5.2.4 on 2025-12-11 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_seed_instructor_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text='Roles that can view this dashboard'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='default_time_range',
            field=models.CharField(choices=[('7d', 'Last 7 Days'), ('30d', 'Last 30 Days'), ('90d', 'Last 90 Days'), ('1y', 'Last Year'), ('all', 'All Time'), ('custom', 'Custom Range')], default='30d', max_length=10),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Show this dashboard by default'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Make this dashboard visible to other users'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='refresh_interval',
            field=models.PositiveIntegerField(default=0, help_text='Auto-refresh interval in seconds (0 = disabled)'),
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widget_type', models.CharField(choices=[('stat_card', 'Stat Card'), ('line_chart', 'Line Chart'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('area_chart', 'Area Chart'), ('table', 'Table'), ('progress_ring', 'Progress Ring'), ('leaderboard', 'Leaderboard')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('data_source', models.CharField(choices=[('user_growth', 'User Growth'), ('enrollment_stats', 'Enrollment Statistics'), ('course_metrics', 'Course Metrics'), ('completion_rates', 'Completion Rates'), ('login_frequency', 'Login Frequency'), ('peak_usage', 'Peak Usage Hours'), ('tenant_comparison', 'Tenant Comparison'), ('device_usage', 'Device Usage'), ('geographic_data', 'Geographic Data'), ('events_by_type', 'Events by Type'), ('popular_courses', 'Popular Courses'), ('active_users', 'Active Users'), ('recent_activity', 'Recent Activity')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=4, help_text='Grid width (1-12)')),
                ('height', models.PositiveIntegerField(default=3, help_text='Grid height (1-12)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard')),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['dashboard', 'order', 'position_y', 'position_x'],
            },
        ),
    ]
