# Generated by Django 5.2 on 2025-04-15 00:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True, help_text='Globally enable/disable notifications for this user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('COURSE_ENROLLMENT', 'Course Enrollment'), ('COURSE_COMPLETION', 'Course Completion'), ('ASSESSMENT_SUBMISSION', 'Assessment Submission'), ('ASSESSMENT_GRADED', 'Assessment Graded'), ('CERTIFICATE_ISSUED', 'Certificate Issued'), ('DEADLINE_REMINDER', 'Deadline Reminder'), ('NEW_CONTENT_AVAILABLE', 'New Content Available'), ('ANNOUNCEMENT', 'Announcement'), ('SYSTEM_ALERT', 'System Alert')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('READ', 'Read'), ('DISMISSED', 'Dismissed')], db_index=True, default='PENDING', max_length=15)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(help_text='The main content of the notification.')),
                ('action_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('delivery_methods', models.JSONField(default=list, help_text="List of methods attempted (e.g., ['EMAIL', 'IN_APP'])")),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('fail_reason', models.TextField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notif_recipient_status_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
