# Generated by Django 5.2.4 on 2025-12-04 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web Browser')], default='WEB', max_length=10)),
                ('token', models.TextField(help_text='FCM registration token or APNS device token')),
                ('device_name', models.CharField(blank=True, help_text="User-friendly device name (e.g., 'Chrome on MacOS')", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False when token becomes invalid')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this device received a notification', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'token')},
            },
        ),
    ]
