# Generated by Django 5.2.4 on 2025-12-08 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platform_settings'),
        ('courses', '0004_add_content_item_is_required'),
        ('notifications', '0002_add_user_device_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_type', models.CharField(choices=[('ALL_TENANT', 'All Users in Tenant'), ('COURSE_ENROLLED', 'Course Enrolled Users'), ('SPECIFIC_USERS', 'Specific Users')], default='ALL_TENANT', max_length=20)),
                ('target_user_ids', models.JSONField(blank=True, default=list, help_text='List of user UUIDs for SPECIFIC_USERS target type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Scheduled time to send announcement', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0, help_text='Number of notifications created from this announcement')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='courses.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
